# Change these first
owner: civilairpatrol # Your GitHub organization or username, where this repository lives
repo: capipedia-uptime # The name of this repository

sites:
  - name: CAPipedia
    url: https://capipedia.cap.gov
    __dangerous__body_down_if_text_missing: 'This page was last edited'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/civilairpatrol/capipedia-uptime/master/assets/cap-logo.svg
  name: CAPipedia Status Page
  introTitle: "**CAPipedia Status Page** is the open-source uptime monitor and status page, powered entirely by GitHub and upptime."
  navbar:
    - title: Status
      href: /
    - title: CAPipedia
      href: https://capipedia.cap.gov
